src/Repositories/Corporation/CorporationRepository.php
This adds the initial SQL queries for Ledger-based screens
=> Services to add initial Ledger queries.

src/Repositories/Character/CharacterRepository.php
required for PR on corp titles in web package
=> Add corporation titles to character sheet

src/Repositories/Corporation/Ledger.php
Fix the where clause for PI to generate the correct sql
=> Fix where clause for PI

src/Repositories/Seat/Stats.php
depends on https://github.com/eveseat/web/pull/48
=> add skills related chart

src/Search/Search.php
update searching tool in order to use it instead the original one.
depends on https://github.com/eveseat/web/pull/56
=> implement a custom method dedicated to search for ApiKey

src/Repositories/Character/Assets.php
the services side of the character nested assets
=> Add assetContents collection for Character Assets view

src/Repositories/Character/Assets.php
=> Character assets

src/database/seeds/ScheduleSeeder.php
Example: from */5 * * * * *  to */5 * * * *
=> Modified cron statements to proper format. Changed from 6 positions to 5

src/Image/Eve.php
Needed for high res image of ships.
http://image.eveonline.com/Type/11567_64.png OK
http://image.eveonline.com/Type/11567_512.png **NOT OK**
http://image.eveonline.com/Render/11567_512.png OK
=> Added support for the 'Render' type to the 'img' Helper

src/Repositories/Character/Mail.php
optimise top mail query by dropping join table and exploit getAffiliationMap in order to retrieve the user character IDs
The usage of joins table cause heavy load on query execution since filter are only applied after messages are fetched (including join operations).
With this commit, filter are applied directly during execution
Thank @flextraaurilen for benchmark
this depends on eveseat/eveapi#20
=> optimise top mail query by dropping join table

src/Repositories/Seat/Stats.php
=> add ACL filters on dashboard stats

src/Repositories/Character/Assets.php, src/Repositories/Character/Bookmarks.php, src/Repositories/Character/Calendar.php, src/Repositories/Character/Character.php, src/Repositories/Character/ChatChannels.php, src/Repositories/Character/Contacts.php, src/Repositories/Character/Contracts.php, src/Repositories/Character/Implants.php, src/Repositories/Character/Industry.php, src/Repositories/Character/Info.php, src/Repositories/Character/Intel.php, src/Repositories/Character/JumpClone.php, src/Repositories/Character/Killmails.php, src/Repositories/Character/Mail.php, src/Repositories/Character/Market.php, src/Repositories/Character/Notifications.php, src/Repositories/Character/Pi.php, src/Repositories/Character/Research.php, src/Repositories/Character/Skills.php, src/Repositories/Character/Standings.php, src/Repositories/Character/Wallet.php
ACL related stuff still need to be refactored.
=> make a complete rewrite of character service according to new ESI models

src/Settings/Seat.php
* add 'esi-planets.manage_planets.v1' to default
=> Add PI as default SSO scope

src/Repositories/Character/Intel.php
depends on
eveseat/web#132
eveseat/console#15
eveseat/eveapi#67
=> update intel for ESI models

src/Repositories/Corporation/Contacts.php
depends on eveseat/eveapi#68
depends on eveseat/web#136
=> upgrade corporation contact in order to implement labels

src/Repositories/Character/Info.php, src/Repositories/Character/MiningLedger.php, src/Repositories/Corporation/MiningLedger.php
depends on eveseat/eveapi#70
depends on eveseat/console#17
depends on eveseat/web#137
=> moving queries to service package for mining ledger

src/Image/Eve.php
faction are provided by ccp on their cdn on alliance route - except drifter :/
=> faction are provided by ccp on their cdn on alliance route

src/Repositories/Configuration/UserRespository.php
=> fix route and user/group relationships on user layouts

src/Repositories/Character/Pi.php
Actual query is not joining tables properly (missing primary key fields).
This commit is fixing them in order to ensure returned extractor information are valid.
Also remove the un-required collection duplication as it's doing nothing special.
=> fix PI extractors query

src/Repositories/Seat/Stats.php
this enabels: https://github.com/eveseat/web/pull/189
=> CharacterMiningTotal ISK

src/Repositories/Character/Industry.php, src/Repositories/Corporation/Industry.php
Update queries from both character and corporation industry services
to use universe_structure table in order to resolve citadels name
=> fix(industry jobs): Fix location field

src/Search/Search.php
The has permission was passed with the global scope which is excluding
character or corporation entity from the permission check.
Since the corp/char scope are requiring the id to be passed into the
query, I've moved some of the logic into the Search sub query.
Basically :
1) retrieve affiliation mapping for the current user
2) search for any wildcard permission for a character
3) search for any character.mail permission for a character
Closes eveseat/seat#424
=> fix(search): Add missing character affiliation filters on mail search

src/Models/HistoricalPrices.php, src/Repositories/Character/MiningLedger.php, src/Repositories/Corporation/MiningLedger.php, src/Repositories/Eve/EvePrices.php, src/Repositories/Seat/Stats.php, src/database/migrations/2018_09_12_181511_create_historical_prices_table.php
* smaller adaptions for supporting value
This is step 2 of 3 for resolving: eveseat/seat#341
=> Lock mining value

src/Repositories/Character/Contracts.php
This PR improves character contracts datatables:
* search by name
* show linked characters
Solves https://github.com/eveseat/seat/issues/438 completely. Solves https://github.com/eveseat/seat/issues/467 partly
=> 438 contract datatables

src/Repositories/Character/Killmails.php, src/Repositories/Character/Wallet.php
This PR needs: https://github.com/eveseat/eveapi/pull/129
=> 459 character killmail

src/ServicesServiceProvider.php
Referring to the documentation https://laravel.com/docs/5.5/packages#migrations
=> use laravels `loadMigrationsFrom()`` method instead of publishing assets

src/Config/services.config.php, src/Repositories/Corporation/Members.php
is prerequisit of: https://github.com/eveseat/web/pull/250
=> Corporation tracking

src/Repositories/Corporation/Killmails.php
is prerequisite of: https://github.com/eveseat/web/pull/266
Testing and closing: https://github.com/eveseat/seat/issues/456
=> Some refactoring in the service and view to be consistent with character view

src/Repositories/Corporation/Wallet.php
* Show 1 tab per division
* refactor service trait
Testing and closing: https://github.com/eveseat/seat/issues/454
is prerequisite of: https://github.com/eveseat/web/pull/267
=> Refactor corporation journal to work as in game.

src/Repositories/Corporation/Market.php
* Test and close https://github.com/eveseat/seat/issues/455
* Add Issued_by column to view
is prerequisite of https://github.com/eveseat/web/pull/268
=> Refactor Corporation Market

src/AbstractSeatPlugin.php, src/ServicesServiceProvider.php
This implement a SeAT specific Provider which have to be inherited by all SeAT package (including plugins) to return proper information and implement auto-discovery into a central place.
**Related to**: eveseat/web#258
=> Version tracker

src/Search/Search.php
https://github.com/eveseat/seat/issues/453
* Using generic partial blades
* disable columns for search which are irrelevant
* disable front end ordering of table as ordering is done in the query.
=> some minor refactoring and testing of 

src/Repositories/Character/Info.php
**DEPENDENCIES :** eveseat/eveapi#164
=> refactor(titles): use relationship instead atomic table

src/Image/Eve.php
since maximum allowed size for invType is 64px, we should only reduce its size when requested one is greater than 64 :p
=> fix(image): address a logic issue related to invType maximum size

src/Image/Eve.php, src/Repositories/Character/Fittings.php, src/Repositories/Character/Intel.php, src/Repositories/Character/Wallet.php
allow item type image to be rendered using 32px and 64px size
address documentation issue regarding namespaces on fittings class
increase logic strength of relationship naming
Dependencies : eveseat/eveapi#165 eveseat/web#313
=> refactor datatable structure

src/Repositories/Corporation/Ledger.php
thanks to initial pull request eveseat/services#79 from soratidus999
this introduce the following new categories into wallet ledger :
- Office Rentals
- Industry Facility Tax
- Reprocessing Tax
- Jump Clone Installation & Activation Tax
- Jump Bridge Activation
Closes eveseat/seat#162
=> feat(corporation): add new categories to wallet ledger

src/Image/Eve.php
Related to eveseat/services#97
=> fix(image): lock retina size to 64px for invType

.styleci.yml, src/Helpers/helpers.php, src/Image/Eve.php, src/ReportParser/Elements/Element.php, src/ReportParser/Elements/Group.php, src/ReportParser/Exceptions/EmptyReportException.php, src/ReportParser/Exceptions/InvalidReportElementException.php, src/ReportParser/Exceptions/InvalidReportException.php, src/ReportParser/Exceptions/InvalidReportGroupException.php, src/ReportParser/Exceptions/MissingReportGroupException.php, src/ReportParser/Exceptions/MissingReportHeaderException.php, src/ReportParser/Parsers/MoonReport.php, src/ReportParser/ReportParser.php, src/Repositories/Character/Mail.php, src/Search/Search.php
- improve mails database structure in order to avoid duplication
- use the new Eve Image Server signatures (which provide some extensibility regarding renders and sizes) : https://developers.eveonline.com/blog/article/from-image-server-to-a-whole-new-image-service-1
- introduce a generic parser engine to handle better EVE reports
=> small things for gen 4

composer.json, src/Socialite/EveOnline/Checker/Claim/AzpChecker.php, src/Socialite/EveOnline/Checker/Claim/NameChecker.php, src/Socialite/EveOnline/Checker/Claim/OwnerChecker.php, src/Socialite/EveOnline/Checker/Claim/ScpChecker.php, src/Socialite/EveOnline/Checker/Claim/SubEveCharacterChecker.php, src/Socialite/EveOnline/Checker/Header/TypeChecker.php, src/Socialite/EveOnline/EveOnlineExtendSocialite.php, src/Socialite/EveOnline/Provider.php
implement JWT token management and switch socialite extension to service package.
replace verify call by JWT validation.
BREAKING CHANGE: require GMP, MBSTRING and OPENSSL extensions
=> feat(auth): switch SSO to v2 endpoints

src/Repositories/Character/Intel.php
The server is trying to pass the 'from' variable to a route but since it was removed from the select in the query it isn't returned anymore and generates an error when loading top mail interactions on the Character Intel page. Minor modifications to keep StyleCI happy too.
=> refactor the queries for intel to remove duplicates and add missing variable from

src/Repositories/Character/Assets.php
since ESI assets endpoint is not providing proper dataset, we need to extract some information from other tables in certain conditions (when root asset is in-space).
For example, when you have a ship in-space, like a Titan, it will not be listed into /characters/{character_id}/assets endpoint.
However, you can retrieve information from /characters/{character_id}/location (for the system name) and /character/{character_id}/ship (for the current ship, including the asset ID to which relay subsequent items)
=> fix(assets): ensure in-space asset can be displayed

src/Repositories/Corporation/Extractions.php
use pivot instead complex dependencies for moon_content, materials and reactions.
=> refactor(moons): simplify relationships

src/database/migrations/2021_01_02_120325_convert_chinese_language_value.php
Since c7bffa83, the chinese langcode changed to 'zh-CN' from 'cn'. Instances upgraded from v3 will have mix with cn and zh-CN.
=> Migrate chinese langcode to 'zh-CN' in user_settings

src/Helpers/helpers.php, src/Image/Eve.php
This pr is a preparation for an upcoming pr to the seat web repo.
Do we have an icon for 'unknown' somewhere? We might want to link it instead of just the empty image we have right now.
=> allow null as id for images

src/Settings/Profile.php
second part of https://github.com/eveseat/web/pull/647
=> remove skins

src/Socialite/EveOnline/Provider.php
Fixes the login with the new sso claim that has been deployed.
This PR is tested and works. I recommend to merge it as soon as possible, as logins are currently broken.
Additionally, it should be merged into 5.0.
=> fix sso login

src/Contracts/EsiClient.php
This PR builds upon https://github.com/eveseat/eseye/pull/98 and expose the new functionality in eseye to seat.
Before this can be merged
- merge and release https://github.com/eveseat/eseye/pull/98
- merge and tag at the same time as https://github.com/eveseat/eveapi/pull/410
=> eseye-bindings: allow access token refreshing

src/Settings/Profile.php
Introduce a page limit setting that is respected by all datatables.
=> Add page limit setting.
