eveseat/services

src/Repositories/Corporation/Assets.php
It appears we're using divisions as top level which are not. Division are always inside
OfficeFolder entry which is a Custom Office. It implies wrong name resolving for structures.
Closes eveseat/seat#337
=> fix(corporation assets): Fix asset top level listing

src/database/migrations/2018_10_05_064533_alter_historical_prices_columns.php
* `average_price` from precision 10 to precision 32 with a scale of 2
* `adjusted_price` from precision 10 to precision 32 with a scale of 2
This change is needed to support prices which needs a higher precision and would resolve: https://github.com/eveseat/seat/issues/451#issuecomment-427259236 
This error is absolutely my causing and i want to apologize for this. I should have copied the migration behavior of `market_prices` instead.
https://github.com/eveseat/eveapi/blob/master/src/database/migrations/2017_12_01_000000_create_market_prices_table.php#L40-L41
=> Alter historical price table columns:

src/Repositories/Character/MiningLedger.php, src/Repositories/Corporation/MiningLedger.php
Since last update applied for price updating, every retrieved ledger entry is leading to a load
from historical_price table. On ledger display, it's causing big issues.
depends on eveseat/eveapi#123 and eveseat/web#225
=> fix(mining ledger): Fix loading time issue due to prices eager-load

src/Repositories/Character/Wallet.php
most notably:
- removal of `get` bool
- removal of `$chunk` variable
- using collections
the removal was done because it was not used anywhere
=> 457 character wallet

src/Search/Search.php
one should use IN..
Bug: 
When using the search as a user with affiliations for all corps and all chars, the search ended up not showing any results, while as a superuser they did. 
a closer look at the query involved, and how it is build showed that it was doing a orWhere with a field name and an array. When checking if a fields value is within an array the use of orWhereIn  is required, to ensure the array is treated as a list for an IN check, rather than as a string/int value for a comparison.
this is also in line with how similar queries are build in other parts of the search.
=> BUGFIX: when looking in a list of ids..

src/Repositories/Corporation/Security.php
Exploit the new Eloquent Pivot relationship to render the corporation
title page properly and avoid excessive memory consummation.
Closes eveseat/seat#595
=> fix(titles): reduce abnormal loop on corp titles page

src/Repositories/Seat/Stats.php
review the way we are counting killmails
with the recent merge of character_killmails
and corporation_killmails into a single
table killmails.
=> refactor(killmails): remove character_killmail

src/Repositories/Character/Character.php, src/Repositories/Corporation/Corporation.php, src/Search/Search.php
Also a work around for an Eloquent column name collision causing the character name column to change to the corporation/alliance name when filtering by the corp/alliance columns respectively.
=> fix(search): Update corporation and alliance relation through affiliation model

src/Repositories/Corporation/Members.php
Related to https://github.com/eveseat/eveapi/pull/197 and https://github.com/eveseat/web/pull/386.
Updated the Members repository to use the RefreshToken relation instead of user, but to also eager load the User model via RefreshToken, the users main character (so we can group the related characters together in DataTables), character name (for sorting/filtering purposes) from UniverseNames and the ship type (added separate column to enable searching, was previously included in the view for the Location column).
=> Update Corporation Members repository to use updated model relations

src/AbstractSeatPlugin.php, src/ServicesServiceProvider.php
due to dependency tree issue, rollback abstract plugin provider from seat package to service package.
the previous state was leading to invalid dependencies tree (we want to install seat, which need x plugin, this plugin need a class which reside in the installing package)
**BREAKING CHANGE**
namespace for `AbstractPluginProvider` switch from `App\Providers\AbstractPluginProvider` to `Seat\Services\AbstractPluginProvider`
eveseat/seat#615
eveseat/api#44
eveseat/console#57
eveseat/eveapi#216
eveseat/notifications#45
eveseat/web#428
=> revert: rollback abstract provider change

src/Repositories/Character/MiningLedger.php, src/Repositories/Corporation/Extractions.php, src/Repositories/Corporation/Structures.php
eloquent does not like internal relation - and generated query can sometimes lead to error (ie: to be able to sort)
this is splitting the mapDenormalize table into 6 specifics sub-tables (most used) :
- regions
- constellations
- systems
- stars
- planets
- moons
=> feat(sde): explode map into specific entities

src/Socialite/EveOnline/Provider.php, src/database/migrations/2020_04_27_231132_convert_sso_scopes_to_list.php
This PR supports PR eveseat/web#424 and allows the JwtToken verification to read the scopes from the session that have been set by the SsoController in eveseat/web instead of the value saved in the settings table, as the scopes may vary depending upon which profile was passed to the SsoController.
=> enhance sso: ability to define scope profiles

composer.json, src/Contracts/EsiClient.php, src/Contracts/EsiResponse.php, src/Contracts/EsiToken.php, src/Helpers/AnalyticsContainer.php
Purpose of this is to provide a way to reduce coupling between SeAT and Eseye.
As a result, this PR is introducing 3 new contracts:
- EsiClient : which must be implemented by a package which want to provide ESI consuming service (ie: Eseye)
- EsiResponse : which must be implemented by a package which want to provide ESI consuming service (ie: Eseye)
- EsiToken: which must be implemented by a package which want to handle token (ie: Eseye)
In order to prevent eseye to be dependent of that package, idea is to provide a new package to provide Eseye within SeAT and which will implement those contracts.
However, I'm still unsure about the way to take regarding token.
In my opinion, client and response **MUST** be implemented by the same package.
However, I don't think the same package **HAVE …
=> Reduce coupling with eseye

phpunit.xml, src/Helpers/helpers.php, tests/CleanCCPHtml/CleanCCPHtmlTest.php
Fixes unicode in ccp richtext from corporation descriptions from this to this:
For more contexts see #support on discord. 
In general, I think `clean_ccp_html` could use an overhaul, because for example links, font sizes and colors are something we could translate aswell.
=> Fix ccp richtext parsing

src/Contracts/HasTypeID.php, src/Contracts/IPriceable.php, src/Helpers/UserAgentBuilder.php, src/Items/EveType.php, src/Items/PriceableEveType.php
* https://github.com/eveseat/seat/discussions/892
* https://github.com/recursivetree/seat-prices-core/tree/master
After the evepraisal shutdown, crytpa and I started working on a new system for seat plugins to get prices of eve items. For accelerated development, we decided to at the beginning not include it in the core, but with a long-term goal to move the full plugin or parts over to the seat core.
This PR is the first step in this migration process. While seat-prices-core isn't completely finished yet, it is far enough to be usable. Additionally, there are parts of the plugin that are already quite stable and unlikely to change going forward. Only these stable parts are being moved over.
This interface describes any object that's associated with a type id. Most notably, this is the …
=> Start integrating recursivetree/seat-prices-core into the seat core

src/Facades/DeferredMigration.php, src/Listeners/RunDeferredMigrations.php, src/Services/DeferredMigrationRegistry.php, src/ServicesServiceProvider.php
While working on a squad system update, I found a migration that depends on the business logic: https://github.com/eveseat/web/blob/fe45844ab67e68761720ce536d0ce481b4ff0f39/src/database/migrations/2020_12_06_220254_upgrade_squads_maj4_min4_hf2.php
This is a bad idea, since when the data the business logic operates on changes, the migrations breaks since the migration updating the data for the business logic didn't run yet. However, this migration is there to remove a broken state, so not running it is not an option.
The solution that this PR enables are deferred migrations: A migration can schedule a closure that should be run after all other migrations have completed. This means the data is already migrated to a state where the business logic is guaranteed to be able process it.
In a …
=> Deferred migrations system

src/Socialite/EveOnline/Provider.php
Latest version of Socialite (https://github.com/laravel/socialite/releases/tag/v5.12.0) added a breaking bug for EVE authentication with this PR : https://github.com/laravel/socialite/pull/684
The fix is to change the list of fields sent in the form body to the token endpoint to no longer include client_id and client_secret because they are provided in the Authorization header. This is the "correct" way to provide client_id/client_secret to an OAuth endpoint (that was the point of the PR on socialite in the first place). So the fix I propose is to accept this behavior and only remove the unecessary fields from the form body.
The Original SeAT error was :
```
Client error: `POST https://login.eveonline.com/v2/oauth/token` resulted in a `400 Bad Request` response: …
```
=> Fix socialite provider

src/Socialite/EveOnline/Provider.php
less than an hour ago the Socialite repository maintainers have reverted their previous PR that created a breaking change on how authentication is handled to the token endpoint. This broke the previous PR I did to fix the 500 error on our side. Now we have a 401 error because the Authentication header is missing.
I created an issue on their repo yesterday about the breaking change, they dismissed it saying they did not maintain our provider (no shit) and closed the issue (so I created the PR here to fix the issue because they would'nt fix it on their repo) and the next day another guy says he has an issue and suddenly the change is reverted... Blows my mind.
Anyway, I tested this one on my local docker env and it works. I basically reimplemented their previous change because it is more in …
=> Fix the socialite provider after they pushed a revert

src/Seeding/AbstractScheduleSeeder.php
@Joseph Null reported that his schedules get reset after restarting. This indeed seems to be the case: https://github.com/eveseat/eveapi/blob/5.0.x/src/database/seeders/ScheduleSeeder.php#L184-L187
On discord, we discussed that existing schedules shouldn't be changed, only missing ones inserted. While looking at this, I noticed that this happens for both eveapi and web. Their seeder are 99% identical in terms of logic for inserting schedules. Since plugins sometimes also need to schedule command, I decided it is worthy it to write a helper for this. This helper belongs in services as far as I know.
=> add schedule seeder helper

src/Contracts/HasTypeIDWithAmount.php, src/Contracts/IPriceable.php, src/Items/EveTypeWithAmount.php, src/Items/PriceableEveType.php
This PR adds a new interface between HasTypeID and IPriceable. The issue is that sometimes, you have a list of items with amount, like a asset list, that doesn't need the price side from IPriceable, but that could profit of the amount side of IPriceable.
I'm currently working on making seat-inventory compatible with the new item ecosystem around the prices plugin and would massively profit of this new interface.
=> feat: add HasTypeIDWithAmount interface

src/Helpers/helpers.php
`ccp_clean_html` converts the messages of evemails into browser-presentable html. The function currently crashes if it is called with `u''` or a few other, specific messages. 
In the implementation, `DOMDocument->loadHTML` doesn't like empty strings. While we do have an empty string check at the top of the function, we apply transformations that can result in an empty string after the check, so it is possible that an empty string reaches `DOMDocument->loadHTML`.
=> fix: ccp_clean_html handle case if removing ccp styling results in empty string
